//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicLeave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicLeave()
        {
            this.Diploma = new HashSet<Diploma>();
        }
    
        public int AcademicLeaveId { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<System.DateTime> DateAcademicLeave { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public Nullable<int> IdNumberGroup { get; set; }
    
        public virtual GroupStudentNumber GroupStudentNumber { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diploma> Diploma { get; set; }
    }
}
