//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diploma
    {
        public int DiplomaId { get; set; }
        public int IdStudent { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
        public int RegistrationNumber { get; set; }
        public int IdQualification { get; set; }
        public int IdSpecialty { get; set; }
        public Nullable<int> IdAcademicLeave { get; set; }
        public int ApplicationSeries { get; set; }
        public int ApplicationNumber { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public Nullable<int> EnrollmentNumber { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<int> ReleaseNumber { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string NameEducational { get; set; }
    
        public virtual AcademicLeave AcademicLeave { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual Student Student { get; set; }
    }
}
