//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public int DisciplineId { get; set; }
        public int IdStudent { get; set; }
        public int IdDisciplinesList { get; set; }
        public int NumberOfHours { get; set; }
        public int Rating { get; set; }
    
        public virtual DisciplineList DisciplineList { get; set; }
        public virtual Student Student { get; set; }
    }
}
