//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int IdOrderList { get; set; }
        public string NumberOrder { get; set; }
        public string TitleOrder { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<int> IdPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
