//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFArchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AcademicLeave = new HashSet<AcademicLeave>();
            this.Diploma = new HashSet<Diploma>();
            this.Discipline = new HashSet<Discipline>();
        }
    
        public int StudentId { get; set; }
        public int IdPerson { get; set; }
        public string Reasonfordeduction { get; set; }
        public Nullable<int> NumberGroup { get; set; }
        public Nullable<int> EnrollmentNumber { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<int> DeductionNumber { get; set; }
        public Nullable<System.DateTime> DeductionDate { get; set; }
        public string GradebookNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicLeave> AcademicLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diploma> Diploma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipline> Discipline { get; set; }
        public virtual GroupStudentNumber GroupStudentNumber { get; set; }
        public virtual Person Person { get; set; }
    }
}
